---
- include: "setup-CentOS7.yml"
  when:
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "7"

- include: "setup-Amazonlinux2.yml"
  when:
      - ansible_facts['distribution'] == "Amazon"